# Dockerfile.worker
FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "app.tasks.worker", "worker", "--loglevel=info", "--queues=payment_intents"]
