"""add unique constraint on merchant_id and title

Revision ID: 4da495f45711
Revises: b5b2890ab30d
Create Date: 2025-07-05 19:20:52.136369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da495f45711'
down_revision: Union[str, None] = 'b5b2890ab30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_merchant_title', 'themes', ['merchant_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_merchant_title', 'themes', type_='unique')
    # ### end Alembic commands ###
