"""Add hashed_password and refresh_token fields to users

Revision ID: 5463d9fb7a0f
Revises: e1d249b0b87f
Create Date: 2025-06-20 19:13:12.923275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5463d9fb7a0f'
down_revision: Union[str, None] = 'e1d249b0b87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'merchant', 'admin', name='userrole'),
               nullable=True)
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
