"""Make category Enum in merchants

Revision ID: 7e5354f7c659
Revises: 5463d9fb7a0f
Create Date: 2025-06-25 09:41:18.111851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5354f7c659'
down_revision: Union[str, None] = '5463d9fb7a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ktv', 'massage', 'art', 'escape_room', 'yoga', 'language_class', 'dance_studio', 'cooking', 'workshop', name='merchantcategory'),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'merchant', 'admin', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'merchant', 'admin', name='userrole'),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('merchants', 'category',
               existing_type=sa.Enum('ktv', 'massage', 'art', 'escape_room', 'yoga', 'language_class', 'dance_studio', 'cooking', 'workshop', name='merchantcategory'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
