"""add unique constraint to slot time

Revision ID: dc85e05f1370
Revises: 4da495f45711
Create Date: 2025-07-08 08:44:22.286775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc85e05f1370'
down_revision: Union[str, None] = '4da495f45711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_theme_slot_time', 'slots', ['theme_id', 'start_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_theme_slot_time', 'slots', type_='unique')
    # ### end Alembic commands ###
